repos:
  - repo: local
    hooks:
      - id: ruff-format
        name: ruff format
        entry: .venv/bin/ruff format --check
        language: python
        types_or: [python, pyi]
      - id: ruff-check
        name: ruff check
        entry: .venv/bin/ruff check
        language: python
        types_or: [python, pyi]
      - id: mypy
        name: mypy
        entry: .venv/bin/mypy
        language: python
        types_or: [python, pyi]
